### ISSUE TITLE
Advice for Compiling FFMpeg linked against OpenH264

### ISSUE THREAD

**Issue by JordanSjodinFaithlife** [Crigges/Prebuild-LGPL-2.1-FFmpeg-with-OpenH264#2]
Do you have any more details on how you compiled FFmpeg linked against libopenh264? I assume I need to make a pkg-config file and point it to the right things so when FFmpeg builds it can find what it needs, but I'm not sure what I am doing exactly. I dont want to build libopenh264 from source but rather link against one of Cisco's pre-built binaries like you have done here

**Comment by Crigges** [comment]
I cross compiled shared openh264 on linux which generated a `libopenh264.dll.a` file. I put this file as lib and the wels/ folder from the source as include in the openh264.pc file: 

```
prefix=/usr/local
libdir=${prefix}/lib  <-- libopenh264.dll.a there
includedir=${prefix}/include <-- wels/ folder there

Name: OpenH264
Description: OpenH264 is a codec library which supports H.264 encoding and decoding. It is suitable for use in real time applications such as WebRTC.
Version: 1.7.0
Libs: -L${libdir} -lopenh264 
Libs.private: -lstdc++
Cflags: -I${includedir}
```

Some legal disclaimer I am pretty unsure about:
h.264 might require license fees in certain countries when used in big scales. Cisco made h.264 "free" by covering the license fees for everybody who uses their binaries. And as far as I understood it, you can never include the .dll into your applications since Cisco needs to keep track of the number of encoders and decoders they gave away to pay the correct amount of fees. This is why every end-user needs to download them separately. If I understood you right you just want to link! to their binaries to get the license fees covered. And here comes the problem I never found an official `.lib` or `.a` file for linking. I assume that isn't a problem at all since you still need to download the `.dll` but some could argue that creating your own lib files makes you use part of own binaries.

**Comment by JordanSjodinFaithlife** [comment]
Thanks for the reply, I'll take a look

**Comment by Crigges** [comment]
I will close this for now, feel free to reopen if you need more advise
